[project]
name = 'Smart-TV-Remote-Dimensional-Displacement-Service'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.backup-remote-functionality-selective-amnesia]
path = 'contracts/backup-remote-functionality-selective-amnesia.clar'
clarity_version = 3
epoch = 'latest'

[contracts.battery-death-show-climax-synchronizer]
path = 'contracts/battery-death-show-climax-synchronizer.clar'
clarity_version = 3
epoch = '3.2'

[contracts.furniture-gap-remote-attraction-algorithm]
path = 'contracts/furniture-gap-remote-attraction-algorithm.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
